### ISSUE TITLE
For 1.8.9

### ISSUE THREAD

**Issue by FuzzySlug** [Chocohead/EU-MJ-Engine#4]
Can you make a version that supports Buildcraft Beta 7.2.8 for Minecraft 1.8.9? Thanks.

**Comment by Chocohead** [comment]
7.2.8 works completely differently to how the 7.99.x versions do, so it would require completely rewriting. Sorry for not being able to help, but 1.8.9 is too old and primitive compared to what is possible with the newer releases.
