### ISSUE TITLE
Minor Bug with Ic2 and buildcraft

### ISSUE THREAD

**Issue by CrankySupertoon01** [Chocohead/EU-MJ-Engine#5]
Ic2 classic should be supported. It causes a ticking tile entity error. Im trying to make a legacy pack with IC2 and Buildcraft and this is the perfect mod. Sadly it doesnt support ic2classic

FIX!

**Comment by Chocohead** [comment]
IC2 Classic lacks a vast swathe of what normal IC2 provides internally, so without that this isn't possible in the same way #2 isn't

**Comment by Trinsdar** [comment]
What exactly isn't available in ic2 classic?

**Comment by Chocohead** [comment]
This is using the XML defined GUIs IC2 uses, the component system for making GUIs, and the `ITEBlock` system for bulk making tile entities. Along side helper methods from the likes of `StackUtil`. It allows it all to work as seemlessly as IC2 can, just at the expense of needing IC2 around to do it.
