### ISSUE TITLE
Requires buildcraftenergy

### ISSUE THREAD

**Issue by Recorpse** [Chocohead/EU-MJ-Engine#6]
It says that this mod req buildcraft energy but when I add buildcraft energy it says its a duplicate. so wtf do I do?

**Comment by Chocohead** [comment]
It is running a slightly older version of BuildCraft than the newest version available, so Forge can unclearly suggest BuildCraft is missing rather than too new. I'm hoping to release an update soon that will support BuildCraft 7.99.18 and 7.99.19
